name: hydracoach
description: "Smart hydration tracking with electrolyte balance"
publish_to: 'none'

# Версия приложения: 0.1.0 (MVP) + номер сборки 1
version: 0.1.2+3

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  intl: ^0.20.2
  fl_chart: ^1.0.0
  flutter_local_notifications: ^19.4.1
  geolocator: ^14.0.2
  http: ^1.5.0
  flutter_animate: ^4.5.2
  permission_handler: ^12.0.1
  
  # FIREBASE - ИСПОЛЬЗУЙТЕ ЭТИ СОВМЕСТИМЫЕ ВЕРСИИ:
  firebase_core: ^3.15.0
  firebase_messaging: ^15.0.0
  firebase_auth: ^5.6.0
  cloud_firestore: ^5.6.0
  timezone: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true